import { Book } from "@/types/app";

export type CategoryData = {
  name: string;
  books: Book[];
};

export const categoryData: CategoryData[] = [
  {
    name: "Romance",
    books: Array.from({ length: 10 }, (_, i) => ({
      id: `r${i + 1}`,
      title: [
        "Love in Paris",
        "Sunset Dreams",
        "Winter's Kiss",
        "Summer Romance",
        "Moonlight Dance",
        "Heart's Desire",
        "Ocean's Promise",
        "Autumn Love",
        "Spring Awakening",
        "Starlit Romance",
      ][i],
      author: ["Jane Doe", "John Smith", "Emily Rose", "Michael Chen", "Sarah Wilson", 
               "David Lee", "Anna Brown", "James Wright", "Lisa Park", "Robert Kim"][i],
      lang: "en",
      placeholder: null,
      cover_url: `https://picsum.photos/200/${300 + i}`,
      preview_text:
        "On the night of turning 18, you were sold by your parents to the most powerful werewolf family in the city. You are forced to mate with the alpha of the group—Lukas, who's known for murdering his brides...",
      price: 25 + Math.floor(Math.random() * 20),
      reading_time: 60 + Math.floor(Math.random() * 60),
      reader_count: Math.floor(Math.random() * 100000) + 1000, // Add random reader count between 1,000 and 101,000
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      deleted: false,
    })),
  },
  {
    name: "Mystery",
    books: Array.from({ length: 10 }, (_, i) => ({
      id: `m${i + 1}`,
      title: [
        "The Hidden Clue",
        "Midnight Detective",
        "The Last Witness",
        "Silent Shadows",
        "Dark Secrets",
        "The Missing Key",
        "Deadly Puzzle",
        "Cold Case",
        "Final Evidence",
        "Mystery Manor",
      ][i],
      author: ["Agatha Chen", "Sherlock Brown", "Nancy Drew", "Arthur Blake", "Patricia Wells",
               "Raymond Black", "Mary Holmes", "Richard Castle", "Jessica Fletcher", "Hercule White"][i],
      lang: "en",
      placeholder: null,
      cover_url: `https://picsum.photos/200/${310 + i}`,
      preview_text: "A thrilling mystery that will keep you guessing...",
      price: 30 + Math.floor(Math.random() * 20),
      reading_time: 90 + Math.floor(Math.random() * 60),
      reader_count: Math.floor(Math.random() * 100000) + 1000, // Add random reader count between 1,000 and 101,000
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      deleted: false,
    })),
  },
  {
    name: "Fantasy",
    books: Array.from({ length: 10 }, (_, i) => ({
      id: `f${i + 1}`,
      title: [
        "Dragon's Quest",
        "The Crystal Sword",
        "Realm of Magic",
        "Ancient Spells",
        "The Lost Kingdom",
        "Wizard's Path",
        "Mythical Beasts",
        "Enchanted Forest",
        "The Last Sorcerer",
        "Portal to Dreams",
      ][i],
      author: ["J.R. Blackwood", "Merlin Grey", "Luna Silverstar", "Drake Fireforge", "Aria Nightshade",
               "Storm Ravenclaw", "Sage Moonweaver", "Crystal Starling", "Phoenix Wright", "River Shadowmend"][i],
      lang: "en",
      placeholder: null,
      cover_url: `https://picsum.photos/200/${320 + i}`,
      preview_text: "An epic fantasy adventure in a magical world...",
      price: 35 + Math.floor(Math.random() * 20),
      reading_time: 120 + Math.floor(Math.random() * 60),
      reader_count: Math.floor(Math.random() * 100000) + 1000, // Add random reader count between 1,000 and 101,000
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      deleted: false,
    })),
  },
  {
    name: "Sci-Fi",
    books: Array.from({ length: 10 }, (_, i) => ({
      id: `s${i + 1}`,
      title: [
        "Space Odyssey",
        "Time Paradox",
        "Quantum Dreams",
        "Android Heart",
        "Stellar Wars",
        "Neural Link",
        "Cosmic Journey",
        "Future's Edge",
        "Digital Horizon",
        "Galaxy's End",
      ][i],
      author: ["Isaac Clarke", "Nova Sterling", "Orion Wells", "Tesla Knight", "Cosmos Jones",
               "Aurora Blake", "Vector Prime", "Nebula Smith", "Quantum Wright", "Galaxy Rose"][i],
      lang: "en",
      placeholder: null,
      cover_url: `https://picsum.photos/200/${330 + i}`,
      preview_text: "A journey through space and time...",
      price: 35 + Math.floor(Math.random() * 20),
      reading_time: 100 + Math.floor(Math.random() * 60),
      reader_count: Math.floor(Math.random() * 100000) + 1000, // Add random reader count between 1,000 and 101,000
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      deleted: false,
    })),
  },
  {
    name: "Horror",
    books: Array.from({ length: 10 }, (_, i) => ({
      id: `h${i + 1}`,
      title: [
        "Haunted House",
        "Midnight Terror",
        "Dark Whispers",
        "The Cursed",
        "Shadow's Edge",
        "Ancient Evil",
        "Night Stalker",
        "Demon's Door",
        "Ghost Stories",
        "The Possession",
      ][i],
      author: ["Edgar Blackwood", "Stephen Night", "Raven Crow", "Mary Shelley", "Howard Phillips",
               "Crimson King", "Blair Woods", "Salem Wright", "Dante Shadow", "Victor Graves"][i],
      lang: "en",
      placeholder: null,
      cover_url: `https://picsum.photos/200/${340 + i}`,
      preview_text: "A spine-chilling tale of horror and suspense...",
      price: 30 + Math.floor(Math.random() * 20),
      reading_time: 80 + Math.floor(Math.random() * 60),
      reader_count: Math.floor(Math.random() * 100000) + 1000, // Add random reader count between 1,000 and 101,000
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      deleted: false,
    })),
  },
];
